name: stratos_agency
description: A social media agency management tool.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  google_sign_in: ^6.2.1
  provider: ^6.1.1
  http: ^1.1.0
  intl: ^0.19.0
  google_generative_ai: ^0.2.0
  flutter_markdown: ^0.6.18+3
  url_launcher: ^6.2.4
  cached_network_image: ^3.3.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
